
language: python
python:
    - "3.5"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

install:
    - python -m pip install -r requirements.dev.txt
    - nvm install 5.12.0
    - npm install -g node-gyp
    - npm install -g https://github.com/wk0206/xml2csv.git

script:
    - coverage run --source os_fdp_adapters -m pytest 

after_success:
    - coveralls

